/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autogestionestudiantil;

/**
 *
 * @author Alumno
 */
public class VistaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnPanelPrincipal = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();
        CartaReportes = new javax.swing.JPanel();
        cartaPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        lblAño = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMaterias = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAlertas = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        btnInscribir = new javax.swing.JButton();
        btnAsistencia = new javax.swing.JButton();
        btnNota = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuA = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuR = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(180, 0));
        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        btnPanelPrincipal.setText("Panel Principal");
        jPanel2.add(btnPanelPrincipal);

        btnPerfil.setText("Perfil del Estudiante");
        jPanel2.add(btnPerfil);

        btnReportes.setText("Reportes");
        jPanel2.add(btnReportes);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        panelCentral.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout CartaReportesLayout = new javax.swing.GroupLayout(CartaReportes);
        CartaReportes.setLayout(CartaReportesLayout);
        CartaReportesLayout.setHorizontalGroup(
            CartaReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        CartaReportesLayout.setVerticalGroup(
            CartaReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );

        panelCentral.add(CartaReportes, "card3");

        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        lblNombre.setText("Nombre: Agustina Bosco");
        jPanel1.add(lblNombre);

        lblCarrera.setText("Carrera: Programacion");
        jPanel1.add(lblCarrera);

        lblAño.setText("2023");
        jPanel1.add(lblAño);

        TablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Materia", "Codigo", "Condicion", "Asistencia", "Promedio"
            }
        ));
        jScrollPane1.setViewportView(TablaMaterias);

        lstAlertas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstAlertas);

        btnInscribir.setText("Inscribir materia");

        btnAsistencia.setText("Registrar asistencia");

        btnNota.setText("Registrar Asistencia");

        btnBaja.setText("Dar de baja");

        javax.swing.GroupLayout cartaPrincipalLayout = new javax.swing.GroupLayout(cartaPrincipal);
        cartaPrincipal.setLayout(cartaPrincipalLayout);
        cartaPrincipalLayout.setHorizontalGroup(
            cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cartaPrincipalLayout.createSequentialGroup()
                        .addComponent(btnInscribir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAsistencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBaja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 116, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cartaPrincipalLayout.setVerticalGroup(
            cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cartaPrincipalLayout.createSequentialGroup()
                        .addGroup(cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnInscribir)
                                .addComponent(btnAsistencia))
                            .addComponent(btnNota, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBaja))
                        .addContainerGap())))
        );

        panelCentral.add(cartaPrincipal, "card2");

        getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

        MenuA.setText("Archivo");

        jMenuItem1.setText("Cerrar");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        MenuA.add(jMenuItem1);

        jMenuBar1.add(MenuA);

        MenuR.setText("Reportes");

        jMenuItem2.setText("Situación General");
        MenuR.add(jMenuItem2);

        jMenuItem3.setText("Materias en Riesgo");
        MenuR.add(jMenuItem3);

        jMenuItem4.setText("Aprobadas");
        MenuR.add(jMenuItem4);

        jMenuBar1.add(MenuR);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CartaReportes;
    private javax.swing.JMenu MenuA;
    private javax.swing.JMenu MenuR;
    private javax.swing.JTable TablaMaterias;
    private javax.swing.JButton btnAsistencia;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnInscribir;
    private javax.swing.JButton btnNota;
    private javax.swing.JButton btnPanelPrincipal;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnReportes;
    private javax.swing.JPanel cartaPrincipal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAño;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JList<String> lstAlertas;
    private javax.swing.JPanel panelCentral;
    // End of variables declaration//GEN-END:variables
}
