/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AutogestionEstudiantil;

/**
 *
 * @author Alumno
 */
public class VistaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnPanelPrincipal = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();
        CartaReportes = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtReporte = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        btnSituacion = new javax.swing.JButton();
        btnMatRiesgo = new javax.swing.JButton();
        btnAprobadas = new javax.swing.JButton();
        lblEstadoReporte = new javax.swing.JLabel();
        cartaPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblCarrera = new javax.swing.JLabel();
        lblAño = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMaterias = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAlertas = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        lblAlertas = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pnlInscripcion = new javax.swing.JPanel();
        lblNomb = new javax.swing.JLabel();
        txtNombreMateria = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblCuatrimestre = new javax.swing.JLabel();
        txtCautrimestre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        btnInscribir = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbAsistencia = new javax.swing.JComboBox<>();
        btnAsistencia = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        btnNota = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuA = new javax.swing.JMenu();
        jMItemCerrar = new javax.swing.JMenuItem();
        MenuR = new javax.swing.JMenu();
        jMItemSituacion = new javax.swing.JMenuItem();
        jMItemMatRiesgo = new javax.swing.JMenuItem();
        jMItemMatAprob = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(180, 0));
        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        btnPanelPrincipal.setText("Panel Principal");
        jPanel2.add(btnPanelPrincipal);

        btnPerfil.setText("Perfil del Estudiante");
        jPanel2.add(btnPerfil);

        btnReportes.setText("Reportes");
        jPanel2.add(btnReportes);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        panelCentral.setLayout(new java.awt.CardLayout());

        CartaReportes.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Reportes Académicos");
        jPanel6.add(jLabel4);

        CartaReportes.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        txtReporte.setEditable(false);
        txtReporte.setColumns(20);
        txtReporte.setLineWrap(true);
        txtReporte.setRows(5);
        txtReporte.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtReporte);

        CartaReportes.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        btnSituacion.setText("Situación general");
        jPanel7.add(btnSituacion);

        btnMatRiesgo.setText("Materias en riesgo");
        jPanel7.add(btnMatRiesgo);

        btnAprobadas.setText("Materias Aprobadas");
        jPanel7.add(btnAprobadas);
        jPanel7.add(lblEstadoReporte);

        CartaReportes.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        panelCentral.add(CartaReportes, "card3");

        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre: Agustina Bosco");
        jPanel1.add(lblNombre);

        lblCarrera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarrera.setText("Carrera: Programacion");
        jPanel1.add(lblCarrera);

        lblAño.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAño.setText("Año: \n2023");
        jPanel1.add(lblAño);

        TablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Materia", "Codigo", "Condicion", "Asistencia", "Promedio"
            }
        ));
        jScrollPane1.setViewportView(TablaMaterias);

        lstAlertas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstAlertas);

        lblAlertas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAlertas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAlertas.setText("Alertas de Asistencia:");

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel4.setLayout(new java.awt.GridLayout(2, 1));

        lblNomb.setText("Nombre:");
        pnlInscripcion.add(lblNomb);

        txtNombreMateria.setColumns(12);
        pnlInscripcion.add(txtNombreMateria);

        lblCodigo.setText("Código:");
        pnlInscripcion.add(lblCodigo);

        txtCodigo.setColumns(7);
        pnlInscripcion.add(txtCodigo);

        lblCuatrimestre.setText("Cuatrimestre:");
        pnlInscripcion.add(lblCuatrimestre);

        txtCautrimestre.setColumns(3);
        pnlInscripcion.add(txtCautrimestre);

        jLabel1.setText("Año:");
        pnlInscripcion.add(jLabel1);

        txtAnio.setColumns(5);
        pnlInscripcion.add(txtAnio);

        btnInscribir.setText("Inscribir materia");
        pnlInscripcion.add(btnInscribir);

        jPanel4.add(pnlInscripcion);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Presente/Ausente:");
        jPanel5.add(jLabel2);

        cmbAsistencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAsistencia.addActionListener(this::cmbAsistenciaActionPerformed);
        jPanel5.add(cmbAsistencia);

        btnAsistencia.setText("Registrar asistencia");
        jPanel5.add(btnAsistencia);

        jLabel3.setText("Nota (0-10):");
        jPanel5.add(jLabel3);

        txtNota.setColumns(4);
        jPanel5.add(txtNota);

        btnNota.setText("Registrar Notas");
        jPanel5.add(btnNota);

        btnBaja.setText("Dar de baja");
        btnBaja.addActionListener(this::btnBajaActionPerformed);
        jPanel5.add(btnBaja);

        javax.swing.GroupLayout cartaPrincipalLayout = new javax.swing.GroupLayout(cartaPrincipal);
        cartaPrincipal.setLayout(cartaPrincipalLayout);
        cartaPrincipalLayout.setHorizontalGroup(
            cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartaPrincipalLayout.createSequentialGroup()
                .addGroup(cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cartaPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(cartaPrincipalLayout.createSequentialGroup()
                                .addGroup(cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cartaPrincipalLayout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(cartaPrincipalLayout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartaPrincipalLayout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(lblAlertas, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(cartaPrincipalLayout.createSequentialGroup()
                                        .addGap(691, 691, 691)
                                        .addGroup(cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(cartaPrincipalLayout.createSequentialGroup()
                                                .addGap(139, 139, 139)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(cartaPrincipalLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(cartaPrincipalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cartaPrincipalLayout.setVerticalGroup(
            cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cartaPrincipalLayout.createSequentialGroup()
                        .addComponent(lblAlertas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2)))
                .addGap(50, 50, 50)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelCentral.add(cartaPrincipal, "card2");

        getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

        MenuA.setText("Archivo");

        jMItemCerrar.setText("Cerrar");
        jMItemCerrar.addActionListener(this::jMItemCerrarActionPerformed);
        MenuA.add(jMItemCerrar);

        jMenuBar1.add(MenuA);

        MenuR.setText("Reportes");

        jMItemSituacion.setText("Situación General");
        MenuR.add(jMItemSituacion);

        jMItemMatRiesgo.setText("Materias en Riesgo");
        MenuR.add(jMItemMatRiesgo);

        jMItemMatAprob.setText("Aprobadas");
        MenuR.add(jMItemMatAprob);

        jMenuBar1.add(MenuR);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMItemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMItemCerrarActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBajaActionPerformed

    private void cmbAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAsistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAsistenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CartaReportes;
    private javax.swing.JMenu MenuA;
    private javax.swing.JMenu MenuR;
    private javax.swing.JTable TablaMaterias;
    private javax.swing.JButton btnAprobadas;
    private javax.swing.JButton btnAsistencia;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnInscribir;
    private javax.swing.JButton btnMatRiesgo;
    private javax.swing.JButton btnNota;
    private javax.swing.JButton btnPanelPrincipal;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSituacion;
    private javax.swing.JPanel cartaPrincipal;
    private javax.swing.JComboBox<String> cmbAsistencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMItemCerrar;
    private javax.swing.JMenuItem jMItemMatAprob;
    private javax.swing.JMenuItem jMItemMatRiesgo;
    private javax.swing.JMenuItem jMItemSituacion;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAlertas;
    private javax.swing.JLabel lblAño;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCuatrimestre;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoReporte;
    private javax.swing.JLabel lblNomb;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JList<String> lstAlertas;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel pnlInscripcion;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtCautrimestre;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombreMateria;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextArea txtReporte;
    // End of variables declaration//GEN-END:variables
}
