/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autogestionestudiantil.Vista;

import autogestionestudiantil.Vista.ControladorAutogestion;
/**
 *
 * @author Alumno
 */
public class VistaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        setTitle("Sistema de Autogestión Estudiantil");
        setLocationRelativeTo(null); 
    }
    public void mostrarCarta(String name) {
        java.awt.CardLayout cl = (java.awt.CardLayout) panelCentral.getLayout();
        cl.show(panelCentral, name);
    }
    public void setTextoEstado(String mensaje) {
        lblEstado.setText(mensaje);
    }
    public void setLabelsPerfil(String nombre, String carrera, String anio) {      
        lblPerfilNombre.setText(nombre);
        lblPerfilCarrera.setText(carrera);
        lblPerfilAnio.setText(anio);
    }
    public void setLabelMateriasCount(int cantidad) {
        lblPerfilMaterias.setText(String.valueOf(cantidad));
    }
    public void limpiarCamposInscripcion() {
        txtNombreMateria.setText("");
        txtCodigo.setText("");
        jsCuatrimestre.setValue(1);
        txtAnio.setText("");
        txtNota.setText("");
    }     
    
    // --- Botones de Navegación Lateral ---
    public javax.swing.JButton getBtnPanelPrincipal() { return btnPanelPrincipal; }
    public javax.swing.JButton getBtnPerfil() { return btnPerfil; }
    public javax.swing.JButton getBtnReportes() { return btnReportes; }
    // --- Botones de Operaciones ---
    public javax.swing.JButton getBtnInscribir() { return btnInscribir; }
    public javax.swing.JButton getBtnAsistencia() { return btnAsistencia; }
    public javax.swing.JButton getBtnInscribirAlumno() { return btnInscribirAlumno; }
    public javax.swing.JButton getBtnNota() { return btnNota; }
    public javax.swing.JButton getBtnBaja() { return btnBaja; }
    public javax.swing.JButton  getBtnVolverPrincipal() { return btnVolverPrincipal; }
    public javax.swing.JSpinner getJsCuatrimestre()     { return jsCuatrimestre;    }
    // --- Elementos del JMenuBar Superior ---
    public javax.swing.JMenuItem getjMItemCerrar() { return jMItemCerrar; }
    public javax.swing.JMenuItem getjMItemSituacion() { return jMItemSituacion; }
    public javax.swing.JMenuItem getjMItemMatRiesgo() { return jMItemMatRiesgo; }
    public javax.swing.JMenuItem getjMItemMatAprob() { return jMItemMatAprob; }
    // --- Componentes de Visualización y Selección ---
    public javax.swing.JTable getTablaMaterias() { return TablaMaterias; }
    public javax.swing.JList<String> getLstAlertas() { return lstAlertas; }
    public javax.swing.JComboBox<String> getCmbAsistencia() { return cmbAsistencia; }
    public javax.swing.JTextArea getTxtReporte() { return txtReporte; }
    // --- Captura de Cajas de Texto (Inputs) ---
    public String getTxtNombreMateria() { return txtNombreMateria.getText().trim(); }
    public String getTxtCodigo() { return txtCodigo.getText().trim(); }
    public String getTxtCuatrimestre() { return jsCuatrimestre.getValue().toString();} 
    public String getTxtAnio() { return txtAnio.getText().trim(); }
    public String getTxtNota() { return txtNota.getText().trim(); }
    public String getTxtNombreAlumno() { return txtNombreAlumno.getText().trim(); }
    public String getTxtCarreras() { return txtCarreras.getText().trim(); }
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnPanelPrincipal = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();
        CartaReportes = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtReporte = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        lblEstadoReporte = new javax.swing.JLabel();
        cartaPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMaterias = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAlertas = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        lblAlertas = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pnlInscripcion = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbAsistencia = new javax.swing.JComboBox<>();
        btnAsistencia = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        btnNota = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        lblNomb = new javax.swing.JLabel();
        txtNombreMateria = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblCuatrimestre = new javax.swing.JLabel();
        jsCuatrimestre = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        btnInscribir = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        lblNomb1 = new javax.swing.JLabel();
        txtNombreAlumno = new javax.swing.JTextField();
        lblCarrera = new javax.swing.JLabel();
        txtCarreras = new javax.swing.JTextField();
        btnInscribirAlumno = new javax.swing.JButton();
        cartaPerfil = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lblTituloPerfil = new javax.swing.JLabel();
        pnlDatosPerfil = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblPerfilNombre = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblPerfilCarrera = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblPerfilAnio = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblPerfilMaterias = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        btnVolverPrincipal = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuA = new javax.swing.JMenu();
        jMItemCerrar = new javax.swing.JMenuItem();
        MenuR = new javax.swing.JMenu();
        jMItemSituacion = new javax.swing.JMenuItem();
        jMItemMatRiesgo = new javax.swing.JMenuItem();
        jMItemMatAprob = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(180, 0));
        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        btnPanelPrincipal.setBackground(new java.awt.Color(0, 81, 135));
        btnPanelPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPanelPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        btnPanelPrincipal.setText("Panel Principal");
        jPanel2.add(btnPanelPrincipal);

        btnPerfil.setBackground(new java.awt.Color(0, 81, 135));
        btnPerfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setText("Perfil del Estudiante");
        jPanel2.add(btnPerfil);

        btnReportes.setBackground(new java.awt.Color(0, 81, 135));
        btnReportes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Reportes");
        jPanel2.add(btnReportes);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        panelCentral.setLayout(new java.awt.CardLayout());

        CartaReportes.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Reportes Académicos");
        jPanel6.add(jLabel4);

        CartaReportes.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        txtReporte.setEditable(false);
        txtReporte.setBackground(new java.awt.Color(196, 218, 250));
        txtReporte.setColumns(20);
        txtReporte.setLineWrap(true);
        txtReporte.setRows(5);
        txtReporte.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtReporte);

        CartaReportes.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel7.add(lblEstadoReporte);

        CartaReportes.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        panelCentral.add(CartaReportes, "card3");

        lblNombre.setBackground(new java.awt.Color(245, 245, 245));
        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Gestión Académica");
        jPanel1.add(lblNombre);

        TablaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Materia", "Codigo", "Condicion", "Asistencia", "Promedio"
            }
        ));
        jScrollPane1.setViewportView(TablaMaterias);

        lstAlertas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstAlertas);

        lblAlertas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAlertas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAlertas.setText("Alertas de Asistencia:");

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel4.setLayout(new java.awt.GridLayout(2, 1));
        jPanel4.add(pnlInscripcion);

        jPanel5.setBackground(new java.awt.Color(196, 218, 250));

        jLabel2.setText("Presente/Ausente:");
        jPanel5.add(jLabel2);

        cmbAsistencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAsistencia.addActionListener(this::cmbAsistenciaActionPerformed);
        jPanel5.add(cmbAsistencia);

        btnAsistencia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAsistencia.setText("Registrar asistencia");
        jPanel5.add(btnAsistencia);

        jLabel3.setText("Nota (0-10):");
        jPanel5.add(jLabel3);

        txtNota.setColumns(4);
        jPanel5.add(txtNota);

        btnNota.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNota.setText("Registrar Notas");
        jPanel5.add(btnNota);

        btnBaja.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBaja.setText("Dar de baja");
        btnBaja.addActionListener(this::btnBajaActionPerformed);
        jPanel5.add(btnBaja);

        jPanel8.setBackground(new java.awt.Color(196, 218, 250));

        lblNomb.setText("Nombre Materia:");
        jPanel8.add(lblNomb);

        txtNombreMateria.setColumns(12);
        jPanel8.add(txtNombreMateria);

        lblCodigo.setText("Código:");
        jPanel8.add(lblCodigo);

        txtCodigo.setColumns(7);
        jPanel8.add(txtCodigo);

        lblCuatrimestre.setText("Cuatrimestre:");
        jPanel8.add(lblCuatrimestre);

        jsCuatrimestre.setModel(new javax.swing.SpinnerNumberModel(1, 1, 2, 1));
        jPanel8.add(jsCuatrimestre);

        jLabel1.setText("Año:");
        jPanel8.add(jLabel1);

        txtAnio.setColumns(5);
        jPanel8.add(txtAnio);

        btnInscribir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInscribir.setText("Inscribir materia");
        jPanel8.add(btnInscribir);

        jPanel11.setBackground(new java.awt.Color(196, 218, 250));

        lblNomb1.setText("Nombre Alumno:");
        jPanel11.add(lblNomb1);

        txtNombreAlumno.setColumns(12);
        jPanel11.add(txtNombreAlumno);

        lblCarrera.setText("Carrera:");
        jPanel11.add(lblCarrera);

        txtCarreras.setColumns(7);
        jPanel11.add(txtCarreras);

        btnInscribirAlumno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInscribirAlumno.setText("Inscribir materia");
        jPanel11.add(btnInscribirAlumno);

        javax.swing.GroupLayout cartaPrincipalLayout = new javax.swing.GroupLayout(cartaPrincipal);
        cartaPrincipal.setLayout(cartaPrincipalLayout);
        cartaPrincipalLayout.setHorizontalGroup(
            cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartaPrincipalLayout.createSequentialGroup()
                .addGroup(cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cartaPrincipalLayout.createSequentialGroup()
                        .addGap(836, 836, 836)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cartaPrincipalLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(cartaPrincipalLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cartaPrincipalLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addGroup(cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAlertas, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartaPrincipalLayout.createSequentialGroup()
                                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cartaPrincipalLayout.setVerticalGroup(
            cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cartaPrincipalLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cartaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cartaPrincipalLayout.createSequentialGroup()
                        .addComponent(lblAlertas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelCentral.add(cartaPrincipal, "card2");

        cartaPerfil.setLayout(new java.awt.BorderLayout());

        lblTituloPerfil.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTituloPerfil.setText("Datos del Estudiante");
        jPanel9.add(lblTituloPerfil);

        cartaPerfil.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        pnlDatosPerfil.setBackground(new java.awt.Color(196, 218, 250));
        pnlDatosPerfil.setLayout(new java.awt.GridLayout(4, 2, 0, 10));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Nombre:");
        pnlDatosPerfil.add(jLabel8);

        lblPerfilNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPerfilNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlDatosPerfil.add(lblPerfilNombre);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Carrera:");
        pnlDatosPerfil.add(jLabel9);

        lblPerfilCarrera.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPerfilCarrera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlDatosPerfil.add(lblPerfilCarrera);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Año de ingreso:");
        pnlDatosPerfil.add(jLabel10);

        lblPerfilAnio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPerfilAnio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlDatosPerfil.add(lblPerfilAnio);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Materias:");
        pnlDatosPerfil.add(jLabel11);

        lblPerfilMaterias.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPerfilMaterias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlDatosPerfil.add(lblPerfilMaterias);

        cartaPerfil.add(pnlDatosPerfil, java.awt.BorderLayout.CENTER);

        btnVolverPrincipal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolverPrincipal.setText("Volver al Panel Principal");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addComponent(btnVolverPrincipal)
                .addContainerGap(443, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(btnVolverPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        cartaPerfil.add(jPanel10, java.awt.BorderLayout.PAGE_END);

        panelCentral.add(cartaPerfil, "card4");

        getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(0, 81, 135));

        MenuA.setBackground(new java.awt.Color(0, 81, 135));
        MenuA.setForeground(new java.awt.Color(255, 255, 255));
        MenuA.setText("Archivo");
        MenuA.setOpaque(true);

        jMItemCerrar.setText("Cerrar");
        jMItemCerrar.addActionListener(this::jMItemCerrarActionPerformed);
        MenuA.add(jMItemCerrar);

        jMenuBar1.add(MenuA);

        MenuR.setBackground(new java.awt.Color(0, 81, 135));
        MenuR.setForeground(new java.awt.Color(255, 255, 255));
        MenuR.setText("Reportes");
        MenuR.setOpaque(true);

        jMItemSituacion.setText("Situación General");
        MenuR.add(jMItemSituacion);

        jMItemMatRiesgo.setText("Materias en Riesgo");
        MenuR.add(jMItemMatRiesgo);

        jMItemMatAprob.setText("Aprobadas");
        MenuR.add(jMItemMatAprob);

        jMenuBar1.add(MenuR);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMItemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMItemCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMItemCerrarActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBajaActionPerformed

    private void cmbAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAsistenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAsistenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }  
       /* Ejecución coordinada con el Controlador */
        java.awt.EventQueue.invokeLater(() -> {
            VistaPrincipal vista = new VistaPrincipal();
            ControladorAutogestion controlador = new ControladorAutogestion(vista);
            vista.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CartaReportes;
    private javax.swing.JMenu MenuA;
    private javax.swing.JMenu MenuR;
    private javax.swing.JTable TablaMaterias;
    private javax.swing.JButton btnAsistencia;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnInscribir;
    private javax.swing.JButton btnInscribirAlumno;
    private javax.swing.JButton btnNota;
    private javax.swing.JButton btnPanelPrincipal;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnVolverPrincipal;
    private javax.swing.JPanel cartaPerfil;
    private javax.swing.JPanel cartaPrincipal;
    private javax.swing.JComboBox<String> cmbAsistencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMItemCerrar;
    private javax.swing.JMenuItem jMItemMatAprob;
    private javax.swing.JMenuItem jMItemMatRiesgo;
    private javax.swing.JMenuItem jMItemSituacion;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jsCuatrimestre;
    private javax.swing.JLabel lblAlertas;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCuatrimestre;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblEstadoReporte;
    private javax.swing.JLabel lblNomb;
    private javax.swing.JLabel lblNomb1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPerfilAnio;
    private javax.swing.JLabel lblPerfilCarrera;
    private javax.swing.JLabel lblPerfilMaterias;
    private javax.swing.JLabel lblPerfilNombre;
    private javax.swing.JLabel lblTituloPerfil;
    private javax.swing.JList<String> lstAlertas;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel pnlDatosPerfil;
    private javax.swing.JPanel pnlInscripcion;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtCarreras;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombreAlumno;
    private javax.swing.JTextField txtNombreMateria;
    private javax.swing.JTextField txtNota;
    private javax.swing.JTextArea txtReporte;
    // End of variables declaration//GEN-END:variables
}
